name: App Checks

on: [pull_request]

jobs:
  android_test:
     name: Test on Android
     runs-on: macos-latest
     timeout-minutes: 20
     defaults:
       run:
         working-directory: app
     steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # sdk: ">=3.5.0 <4.0.0"
          flutter-version: 3.41.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install
        run: |
          flutter pub get
      - name: Lint
        run: |
          flutter analyze
      - name: Tests
        run: |
          flutter test
      - name: Build
        run: |
          touch .env
          echo "BIBLIO_API_URL=${{ secrets.BIBLIO_API_URL }}" >> .env
          echo "DIGITALOCEAN_WEBSECURE_TOKEN=${{ secrets.DIGITALOCEAN_WEBSECURE_TOKEN }}" >> .env
          flutter build apk --dart-define-from-file=.env
          flutter build appbundle --dart-define-from-file=.env
      # flutter build ios --dart-define-from-file=.env
      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-report
          path: '**/build/reports/androidTests/connected/'
